language: python

python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master
        - develop

install:
    - sudo apt-get install -qq nginx
    - pip install -IM zetalibrary
    - pip install -IM pylama

script: 
    - make audit
    - make test
