language: python

python:
    - "2.7"

branches:
    only:
        - master
        - develop

before_install:
    - sudo apt-get install -qq supervisor nginx

install:
    - pip install -IM pylama

script: make test
